### ISSUE TITLE
Incorrect String Similarity Calculation Between COLORSTRIP and DATASET_COLORSTRIP

### ISSUE THREAD

**Issue by TongZhou2017** [markvanderloo/stringdist#106]
**Description:** I'm encountering an issue with the stringdist package in R. When calculating string distances, stringdist::stringdist() returns 'COLLAPSE' as being closer to 'COLORSTRIP' than 'DATASET_COLORSTRIP', even though 'DATASET_COLORSTRIP' should be a more relevant match in terms of context.

**Reproducible Example:**

```r
type <- 'COLORSTRIP'
type_names <- c('COLLAPSE', 'PRUNE', 'SPACING', 'TREE_COLORS', 'DATASET_STYLE',
                'DATASET_TEXT', 'DATASET_COLORSTRIP', 'DATASET_BINARY', 'DATASET_GRADIENT',
                'DATASET_HEATMAP', 'DATASET_SYMBOL', 'DATASET_EXTERNALSHAPE', 'DATASET_DOMAINS',
                'DATASET_MULTIBAR', 'DATASET_BOXPLOT', 'DATASET_LINECHART', 'DATASET_PIECHART',
                'DATASET_IMAGE', 'POPUP_INFO')

# Find the closest match using stringdist
if (type %in% type_names) {
  type = type
} else {
  type = as.character(type_names[which.min(stringdist::stringdist(type, type_names))])
}
print(type)
```

**Expected Behavior:**

The function should return 'DATASET_COLORSTRIP' as the closest match to 'COLORSTRIP' because it shares a more specific contextual meaning.

**Actual Behavior:**

The function incorrectly returns 'COLLAPSE' as the closest match, which is not contextually relevant.

**Suggested Fix:**

It may be useful to either:

- Use a different string distance metric that prioritizes contextual relevance, or

- Provide additional context-based weighting for string similarity, especially for terms related to specific datasets or categories.

I would appreciate any guidance on improving this behavior or any fixes to make the function more contextually aware.

**Comment by markvanderloo** [comment]
Hi, please see the documentation on how string distances are computed.
