### ISSUE TITLE
Transpose on single argument

### ISSUE THREAD

**Issue by cpoonolly** [markvanderloo/stringdist#28]
Think I found an interesting bug. Looks like when a single argument is passed to stringdistance matrix, the resulting matrix is transposed. Seems to happen independently of the method being used as well.
```
> stringdist::stringdistmatrix(c("foo", "bar"), c("foo", "a", "b"), method = "hamming")
     [,1] [,2] [,3]
[1,]    0  Inf  Inf
[2,]    3  Inf  Inf
```
```
> stringdist::stringdistmatrix(c("foo"), c("foo", "a", "b"), method = "hamming")
     [,1]
[1,]    0
[2,]  Inf
[3,]  Inf
```

**Comment by markvanderloo** [comment]
It's fixed in the repo now. Thank for reporting!

**Comment by cpoonolly** [comment]
Awesome! Thank you!
