### ISSUE TITLE
stringsim function

### ISSUE THREAD

**Issue by markvanderloo** [markvanderloo/stringdist#29]
Most string distances (except perhaps the ones based on string kernels) have a natural and easily computed minimum and maximum. I could add a ```stringsim``` function that returns a similarity measure between 0 and 1.

**Comment by djvanderlaan** [comment]
I already started on this and except a test that fails for qgram are almost ready implementing this. I called the function `similarity` but perhaps `stringsim` is better. 
Op 1 jun. 2015 10:36 PM schreef Mark van der Loo <notifications@github.com>:Most string distances (except perhaps the ones based on string kernels) have a natural and easily computed minimum and maximum. I could add a stringsim function that returns a similarity measure between 0 and 1.

**Comment by markvanderloo** [comment]
Awesome!

Op 22:47 MA 1 Jun 2015 schreef Jan van der Laan <notifications@github.com>:

**Comment by djvanderlaan** [comment]
Pushed code to `similarity` branch (f9d59ed32c6cf320028b05a94ca82297edfca13a). Mark, could you review the code.

**Comment by markvanderloo** [comment]
Reviewed and looks great. Thanks!
