### ISSUE TITLE
stringdist gives incorrect result when given weights

### ISSUE THREAD

**Issue by zaprice** [markvanderloo/stringdist#37]
When given weights, stringdist will sometimes give an incorrect result. It can even be inconsistent with itself when weights are adjusted by a common factor.

Example:
```r
stringdist("ABC", "BC", method = "lv") # Returns 1, as it should
stringdist("ABC", "BC", method = "lv", weight = c(i=.1, d=.1, s=.1)) # Returns .2, should be .1
stringdist("ABC", "BC", method = "lv", weight = c(i=.1, d=.1, s=1)) # Returns 1, should be .1
```
This differs from what adist returns for the same inputs, too:
```r
adist("ABC", "AB") # Returns 1
adist("ABC", "AB", costs = c(insertions=.1, deletions=.1, substitutions=.1)) # Returns .1
adist("ABC", "AB", costs = c(insertions=.1, deletions=.1, substitutions=1)) # Returns .1
```

Version 0.9.2, installed from CRAN.

**Comment by markvanderloo** [comment]
Confirmed. That's a bug. Thanks for reporting!

**Comment by markvanderloo** [comment]
fixed now. New beta of version 0.9.3 is on my ```drat``` repo. Try
```
drat::addRepo("markvanderloo")
install.packages("stringdist")
stringdist("ABC", "BC", method = "lv", weight = c(i=.1, d=.1, s=.1))
```
Thank you good sir, for reporting. You are now officially immortalized in the stringdist NEWS file.

**Comment by zaprice** [comment]
Thanks for the speedy fix!
