### ISSUE TITLE
word-qgrams as well as character-qgrams

### ISSUE THREAD

**Issue by zachmayer** [markvanderloo/stringdist#39]
Sometimes text data is long and is better thought of as being broken up into "words" rather than "characters."

Your qgram tokenizer is extremely fast and I've found it to be incredibly useful, but I still find myself looking for a fast word-ngram tokenizer.

**Comment by markvanderloo** [comment]
I'm glad you asked this, because this means you can test the beta versions of my `hashr` and `stringdist` packages (code below)  ;-).

Under the hood all distance methods in `stringdist` work on integers. So I have exposed methods for `stringdist`, `stringdistmatrix` and `amatch` that compute distances between lists of integer vectors. (note that BOTH arguments to `stringdist` must be list to have this work properly -- it is a beta version).

Now all you have to do is to use `strsplit` to split text into words and to hash every word to integer. Since no package is capable of doing this AFAIK. I wrote the `hashr` package (not on CRAN yet) to do this for you. Below is a workflow example.

At the moment the `qgrams` function is not overloaded yet but it will be.

```
# install beta-versions from my drat repo
library(drat)
drat::addRepo("markvanderloo")
install.packages(c("hashr","stringdist"))

# load the libs
library(hashr)
library(stringdist)

# some texts
text1 <- "mary had a little lamb"
text2 <- "a little lamb had mary"

# split into words
words1 <- strsplit(text1,"[[:blank:]]")
words2 <- strsplit(text2,"[[:blank:]]")

# hash each word
s1 <- hash(words1)
s2 <- hash(words2)

# compute word-wise distance between texts.
stringdist(s1,s2,method="dl")
```

**Comment by zachmayer** [comment]
Awesome!  I'll check out hashr.  Can you let me know when the qgrams function does word ngrams?

I'm working on some text modeling, and the slowest part of my pipeline is turning texts into matrices of documents - ngrams.  qgram solves my problem for character ngrams, but I want it to do word ngrams too =D.

**Comment by markvanderloo** [comment]
It seems that the recently released [quanteda](http://www.r-pkg.org/pkg/quanteda) package can do what you want directly. [see also here, in the vignette](https://cran.r-project.org/web/packages/quanteda/vignettes/quickstart.html#natural-language-processing-tools).

**Comment by markvanderloo** [comment]
The point is that doing word-grams isn't quite that simple. You need to think about end-of-word analyses, which is language and locale/encoding dependent. So I'm actually happy that `quanteda` is doing this. 

By the way, I opted for writing a bunch of new functions like `seqdist`, `seq_amatch` and `seq_qgrams` for analyzing integer sequences in stead of the overloading described above. Main reason: not all distance metrics for strings are relevant for integer sequences (e.g. soundex).

**Comment by markvanderloo** [comment]
Oh, what the hell. Here's a wordgram function, based on hashr and stringdist. Not tested very well and I don't know how it compares speedwise with `quanteda`, but it seems to work.

```
install.packages("hashr")
drat::addRepo("markvanderloo")
install.packages("stringdist")

wordgrams <- function(..., q=1L, split="[[:blank:]]+"){
  L <- lapply(list(...),function(x) strsplit(x,split=split)[[1]])

  q = 2
  split = "[[:blank:]]"
  L <- lapply(list("mary had a little lamb","a little lamb had mary")
              , function(x) strsplit(x,split=split)[[1]])
  H <- hashr::hash(L)
  Q <- do.call("seq_qgrams", list(.list=H, q=q))
  # create lookup table 
  H <- unlist(lapply(seq_along(L),function(i) setNames(H[[i]],L[[i]])))
  # find names there; store in matrix
  Qnms <- matrix(names(H)[apply(Q[,seq_len(q),drop=FALSE],2,match,H)]
                 ,ncol=q , dimnames=list(NULL,paste0("g",seq_len(q))))
  cbind(as.data.frame(Qnms),as.data.frame(Q[,-seq_len(q),drop=FALSE]))
  
}
```
and here's a small test
```
s1 <- "Mary had a little lamb"
s2 <- "a little lamb mary had"

> wordgrams(x=s1,y=s2,q=2)
      g1     g2 n.V1 n.V2
1   mary    had    1    0
2    had      a    1    0
3    had   mary    0    1
4 little   lamb    1    1
5   lamb    had    0    1
6      a little    1    1
```

**Comment by markvanderloo** [comment]
Ok, I compared my function with `quanteda::tokenize`. At first it was 3 times slower, but using `Rprof` I could see that most of the time was gobbled up by `base::strsplit`. However, if I use the `stringr::str_split` function, which is based on the `stringi` package. `wordgrams` is about five times faster, and `tokenize` has not even counted the ngrams yet.

```
install.packages("hashr")
drat::addRepo("markvanderloo")
install.packages("stringdist")
library(stringdist)
library(quanteda)
library(stringr)

wordgrams <- function(..., q=1L, split="[[:blank:]]+"){
  L <- lapply(list(...),function(x) stringr::str_split(x,pattern=split)[[1]])
  H <- hashr::hash(L)
  Q <- do.call("seq_qgrams", list(.list=H, q=q))
  # create lookup table 
  H <- unlist(lapply(seq_along(L),function(i) setNames(H[[i]],L[[i]])))
  # find names there; store in matrix
  Qnms <- matrix(names(H)[apply(Q[,seq_len(q),drop=FALSE],2,match,H)]
                 ,ncol=q , dimnames=list(NULL,paste0("g",seq_len(q))))
  cbind(as.data.frame(Qnms),as.data.frame(Q[,-seq_len(q),drop=FALSE]))
  
}
  
# test set from quanteda
inaug <- as.list(inaugTexts)
microbenchmark::microbenchmark(times=25
  ,stringdist = do.call("wordgrams",list(.list=inaug,q=2))
  ,quanteda = tokenize(inaugTexts,ngrams = 2)
)

```
The output is as follows (on my machine)
```
Unit: milliseconds
       expr       min        lq      mean    median        uq       max neval
 stringdist  34.53309  34.63387  35.43675  34.75398  35.11343  46.13655    25
   quanteda 167.61371 169.29537 182.00997 170.93019 182.37906 325.82415    25
```

**Comment by zachmayer** [comment]
hahah, I'm lucky this kind of code is so fun to write.  Thank you!

I've also been in touch with the quanteda about some ways to speed up their functions.  I slightly prefer using stringdist/hashr as it's a lighter-weight package.

I'm probably going to find myself re-implementing a lot of the quanteda functionality, for what will probably turn out to be silly reasons....

**Comment by markvanderloo** [comment]
:-D

Since for a good tokenizer, I need to depend on `stringr` (which brings `stringi`, `Rcpp` and what not) I'm not going to include the wordgram function in stringdist. I like to keep it a more lightweight infrastructural package.

I want to add a few more things to stringdist before releasing it to CRAN again. After that, I'll talk to the quanteda people to see if they are open to depending on stringdist/hashr as infrastructure for their tokenization functionality.

I'm going to close this issue for now.

Cheers,
Mark

**Comment by zachmayer** [comment]
Thanks!  That makes sense, I'll just use your function above for now, as I'm already importing stringi.

**Comment by markvanderloo** [comment]
Turns out, I made a mistake in the benchmark (I thought it was to good to be true :)).
See this [this gist](https://gist.github.com/markvanderloo/9ae6a15f7d74a0159aec) for updated code.
