### ISSUE TITLE
stringdist with 'jw' method not producing symmetric distance

### ISSUE THREAD

**Issue by gtumuluri** [markvanderloo/stringdist#42]
Hi,

Please see below problem I have with asymmetry in the distance for 'jw' method. This is causing a problem in my data set. In fact, the specific strings I test in my data set (can't share due to PHI), the distance equality test for symmetry fails even more badly with much larger delta on the reverse.

Thank you

> round(stringdist('HENCERANGE3058RUNAWAY2HELLCITYAA12345', 'RANCHRANGE3058RUNAWAY2HELLCITYAA12345', method = 'jw'), 8) == round(stringdist('RANCHRANGE3058RUNAWAY2HELLCITYAA12345', 'HENCERANGE3058RUNAWAY2HELLCITYAA12345', method = 'jw'), 8)
[1] FALSE
> 'HENCERANGE3058RUNAWAY2HELLCITYAA12345' == 'HENCERANGE3058RUNAWAY2HELLCITYAA12345'
[1] TRUE
> 'RANCHRANGE3058RUNAWAY2HELLCITYAA12345' == 'RANCHRANGE3058RUNAWAY2HELLCITYAA12345'
[1] TRUE
> 
> stringdist('HENCERANGE3058RUNAWAY2HELLCITYAA12345', 'RANCHRANGE3058RUNAWAY2HELLCITYAA12345', method = 'jw')
[1] 0.2550837
> stringdist('RANCHRANGE3058RUNAWAY2HELLCITYAA12345', 'HENCERANGE3058RUNAWAY2HELLCITYAA12345', method = 'jw')
[1] 0.2265122

**Comment by markvanderloo** [comment]
Thanks for reporting this. I have to look into this, perhaps the jw distance is not symmetric by definition after all (the 'definition' is pretty vague actually). As a workaround, you could average over the distances `a -> b` and `b -> a`.

**Comment by djvanderlaan** [comment]
Mark,

I was trying some code that uses my old implementation of the Jaro similarity and decided to try this example. In my implementation (which follows the original of Jaro quite close), both strings have the same similarity score. I also had a look at the algorithm and could not find a reason why the score should not be symmetric. 

Below the comparison: 

```{R}
> dyn.load("jaro.so")
> 
> .Call("jw", 'HENCERANGE3058RUNAWAY2HELLCITYAA12345', 'RANCHRANGE3058RUNAWAY2HELLCITYAA12345')
[1] 0.8782497
> .Call("jw", 'RANCHRANGE3058RUNAWAY2HELLCITYAA12345', 'HENCERANGE3058RUNAWAY2HELLCITYAA12345')
[1] 0.8782497
> 
> 
> .Call("jw", 'HENCERANGE3058RUNAWAY2HELLCITYAA12345', 'RANCHRANGE3058RUNAWAY2HELLCITYAA12345') ==
+ .Call("jw", 'RANCHRANGE3058RUNAWAY2HELLCITYAA12345', 'HENCERANGE3058RUNAWAY2HELLCITYAA12345')
[1] TRUE
> 
> 
> library(stringdist)
> 
> 1-stringdist('HENCERANGE3058RUNAWAY2HELLCITYAA12345', 'RANCHRANGE3058RUNAWAY2HELLCITYAA12345', method = 'jw', p=0)
[1] 0.7449163
> 1-stringdist('RANCHRANGE3058RUNAWAY2HELLCITYAA12345', 'HENCERANGE3058RUNAWAY2HELLCITYAA12345', method = 'jw', p=0)
[1] 0.7734878
```

The strange thing is that the scores are not only not symmetric, but there is also a difference between the scores from `stringdist` and my implementation. This is not the case for other strings:

```{R}
> .Call("jw", 'shackleford', 'shackelford')
[1] 0.969697
> 1-stringdist('shackleford', 'shackelford', method = 'jw', p=0)
[1] 0.969697
> 
> .Call("jw", 'jones', 'johnson')
[1] 0.7904762
> 1-stringdist('jones', 'johnson', method = 'jw', p=0)
[1] 0.7904762
```

Both give the same results; both equal to results from literature. 

For code see https://gist.github.com/djvanderlaan/9bd1ff9830c3a2326b8f

**Comment by djvanderlaan** [comment]
Smaller strings with the same behaviour are:

```
HENCERANGE
RANCHRANGE
````

**Comment by djvanderlaan** [comment]
The problem seems to be with counting the transpositions:

```{R}
> 1 - stringdist(str1, str2, method="jw", p = 0, weight = c(1, 1, 1))
[1] 0.825
> 1 - stringdist(str2, str1, method="jw", p = 0, weight = c(1, 1, 1))
[1] 0.7833333
> 1 - stringdist(str1, str2, method="jw", p = 0, weight = c(1, 1, 0.000001))
[1] 0.5333336
> 1 - stringdist(str2, str1, method="jw", p = 0, weight = c(1, 1, 0.000001))
[1] 0.5333336
```

The algorithm matches the following letters:
```
HNCRANGE
NCHRANGE
```

This results in 3 half-transpositions (the H and the N don't match; the N and C; and the C and H). In the original algorithm this results in 1 full transposition because of rounding. `stringdist` counts 1 transposition or 2 transpositions depending on the order of the words for some reason

```{R}
> nmatch <- 8
> ntransp <- c(1:2)
> l <- 10
> 1/3*(nmatch/l + nmatch/l + (nmatch-ntransp)/nmatch)
[1] 0.8250000 0.7833333
```

**Comment by desource90** [comment]
I'm also encountering an issue with counting transpositions, probably related to the issue djvanderlaan pointed out.

```
> stringdist('RICK WARREN', 'WARREN BUFFET',method='jw', p = 0, weight = c(1, 1 , 1))
[1] 0.5131535
```

Based on the result, the number of transpositions and matches must be this..
```
> m = 7; t = 5; s1 = 13; s2 = 11
> 1 - (1/3)*(m/s1 + m/s2 + (m-t)/m)
[1] 0.5131535
````

The maximum number of transpositions should be 7, but the algorithm seems to have counted 10 transpositions.

**Comment by markvanderloo** [comment]
I looked into this and found the lines of code that cause this asymmetry. Funny enough, it passes all the tests I found in Jaro's and Winkler's papers so it went unnoticed until now. I'll rewrite the transposition counter.

**Comment by markvanderloo** [comment]
I pushed an update to the `fixjaro` branch.

Before I merge it with the master for push to CRAN I'd appreciate it if someone would try it out.

You can install the updated version from my drat repo:

```
drat::addRepo("markvanderloo")
install.packages("stringdist")
```

Check the version number (should be 0.9.4)
```
packageVersion("stringdist")
```

**Comment by gtumuluri** [comment]
> drat::addRepo("markvanderloo")
> install.packages("stringdist")
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository http://markvanderloo.github.io/drat/bin/macosx/mavericks/contrib/3.1
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository http://markvanderloo.github.io/drat/bin/macosx/mavericks/contrib/3.1

**Comment by markvanderloo** [comment]
For OSX (and Windows) you need to explicitly tell `install.packages` to install from source.

```
drat::addRepo("markvanderloo")
install.packages("stringdist", type="source")
```
