### ISSUE TITLE
Normalise weights in jaro distance

### ISSUE THREAD

**Issue by djvanderlaan** [markvanderloo/stringdist#43]
In `jaro.C` the value of `3.0` is hard coded:

```{C}
  } else {
    d = 1.0 - (1.0/3.0)*(w[0]*m/((double) x) + w[1]*m/((double) y) + w[2]*(m-t)/m);
  }
```

This should be the sum of the weights. Otherwise, the score is no longer necessarily between 0 and 1.

**Comment by djvanderlaan** [comment]
Fix committed; Probably needs test case

**Comment by markvanderloo** [comment]
:+1: Just adapted the tests to match this case.
