### ISSUE TITLE
stringdistmatrix gives unexpected output for large input vectors

### ISSUE THREAD

**Issue by touwwouter** [markvanderloo/stringdist#45]
When `stringdistmatrix` is called using a large single input vector, the result is a distance matrix of class `dist` with fewer elements than expected.

```
many_words <- sapply(1:100000, function(x) paste(sample(letters, 10, replace=T),
                                                 collapse=""))
# Needs a lot of memory
d <- stringdist::stringdistmatrix(many_words, method = "jw")
size <- attr(d, "Size")
stopifnot(inherits(d, "dist"))
stopifnot(size == length(many_words))
stopifnot(length(d) == size*(size - 1)/2)
# Error: length(d) == size * (size - 1)/2 is not TRUE
# > length(d)
# [1] 704982704
# > size*(size - 1)/2
# [1] 4999950000
```

For smaller character vectors I did not encounter any problems:
```
few_words <- sapply(1:1000, function(x) paste(sample(letters, 10, replace=T),
                                              collapse=""))
d <- stringdist::stringdistmatrix(few_words, method = "jw")
stopifnot(inherits(d, "dist"))
size <- attr(d, "Size")
stopifnot(size == length(few_words))
stopifnot(length(d) == size*(size - 1)/2)
# No errors raised
```

I can provide more info when necessary.

**Comment by djvanderlaan** [comment]
This is caused by an integer overflow. R and stringdist indexes matrices/vector by default with integers. The resulting matrix in your case is larger than the maximum integer:

```
> .Machine$integer.max
[1] 2147483647
> 4999950000-2*.Machine$integer.max
[1] 704982706
```

The latest versions of R have large vector support, so on the R side support should be possible (not sure if dist objects support this). However, support will need to be added to stringdist. 

I would expect that problems of this size will take too long on a single machine. Did you calculate/predict the run times for this.

**Comment by touwwouter** [comment]
Thanks. I would expect a warning from the current version of stringdistmatrix, though, since it took me a while before I figured out the source of my downstream problems.

On my workstation with 40 threads, the run time is quite acceptable:
```
   user  system elapsed 
689.892   9.048  23.474
```

On a single thread the elapsed time is slightly over 8 minutes:
```
   user  system elapsed 
489.896   7.756 497.547 
```

**Comment by markvanderloo** [comment]
Jan's answer is correct. Stringdist does not support long vectors yet, on
in or output side. I've had this as an issue on the list for a while now.
See issue #14. Perhaps it is time to do it :-).
Op 23 dec. 2015 17:53 schreef "touwwouter" <notifications@github.com>:

**Comment by markvanderloo** [comment]
Wouter, I've added support in the development version that you can install from my drat repo:

```
# if  you don't have it
install.packages("drat")
drat::addRepo("markvanderloo")
install.packages("stringdist")
```
 I can't run the test you describe since it requires allocating about 18G of storage for the output.

It would be great if you could give it a whirl.

**Comment by touwwouter** [comment]
My machine with 64GB memory cannot allocate enough memory for 10^5 words, but the test passes for an input vector with 66000 elements.

**Comment by markvanderloo** [comment]
Ok,thanks for trying that. I'll implement it for full matrices as well
before submitting the update to CRAN.
Op 24 dec. 2015 15:19 schreef "touwwouter" <notifications@github.com>:
