### ISSUE TITLE
[question] complexity on parameter `q`

### ISSUE THREAD

**Issue by dselivanov** [markvanderloo/stringdist#53]
Hi. I have a question regarding complexity of algorithm for q-gram family distances depending on `q` parameter.
I have quite large dataset (~0.5m strings) and trying to calculate q-gram family distances (jaccard, cosine, qgram). I noticed, that to `q=3`, time is ~ 30sec. For `q=4` => ~ 180sec. For `q=5` ~1800 sec.

However for jaccard intuitively it should not dependency on q size: construction of 2 hash-sets does not denend on q and set intersection/union also doesn't depend on q. 
Do I miss something, or internal algorithm depends on `q` (it seems even not linearly)?

I use latest `0.9.4.4` verion from CRAN.

**Comment by markvanderloo** [comment]
The algorithm currently stores q-grams in a tree rather than a hash table. The size of the tree depends on the number of unique q-grams encountered. The number of possibilities, given some alphabet grows exponentially, but the actual growth depends on the language and slows down when q is increased enough.

The tree structure is pretty optimized, using a custom doubling memory allocator.

I have considered (and am still considering) to work with a hash table but determining an optimal size is not entirely trivial.

**Comment by dselivanov** [comment]
Thanks for answer. Do I understand correctly that tree is global for all strings? Because if tree is constructed for each pair of strings then intuitively it can be more effective because size of tree will be small (due to limited number of possibilities - data is small, so exponential nature won't have big impact). But in this case there will be much more memory allocations and deallocations...

**Comment by markvanderloo** [comment]
Yes, there is one tree for each thread that is re-used. This is to avoid too many calls to the memory allocator.

**Comment by dselivanov** [comment]
So in that case may be it will be not too hard to simultaneously calculate 3 measures `jaccard`, `cosine`, `qgram` on the same tree (allow several distances on R front-end)?  I expect calculation time for 3 distances will almost the same as any single one.

Also is there any possibility to check how many time spent for tree construction and for actual lookups?

**Comment by markvanderloo** [comment]
Yes those times should be about the same. I guess the easiest way to time the C-code is to use [oprofile](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#oprofile-and-operf). I have done this while developing the code, but its been a while.

**Comment by dselivanov** [comment]
Can we add possibility of simultaneous  calculation of q-gram family distances to feature request list please :-)
And thanks a lot for `oprofile`, didn't know about this.

**Comment by markvanderloo** [comment]
There is one alternative to consider: you could use `qgrams` to compute the actual observed q-grams and compute distances between the rows. I'll think about the multiple-distance calculation, but one 'problem' is that it would change the output format of `stringdist`/`stringdistmatrix`/`stringsim`. OTOH I do get the performance issue.
