### ISSUE TITLE
[Feature Suggestion] Return String-distance Dataframe

### ISSUE THREAD

**Issue by bschneidr** [markvanderloo/stringdist#55]
Given the recent proliferation of tools for working with data frames (e.g. `dplyr` and `tidyr`), I often find it helpful to convert distance matrices to data frames. Even though data frames are often much less memory efficient than matrices and are often slower for calculations, their ease-of-use these days makes them appealing.

While converting a distance matrix to a data frame can be done fairly quickly, it would be helpful to have a function in the `stringdist` package do this 'out-of-the-box'.

Below is example of how such a string distance data frame could be constructed and how it might look:

      x <- c("apple", "banana", "peach")
      y <- c("ape", "bandana", "pitch")
  
    stringdist::stringdistmatrix(a = x,
                                 b = y,
                                 useNames = "strings") %>%
      as.data.frame %>%
      tibble::rownames_to_column("a") %>%
      tidyr::gather(key = "b", value = "String_Distance", -a)

**Comment by markvanderloo** [comment]
hi @bschneidr ,

This question is not really specific to `stringdist`, since there are many pkgs/functions out there that compute distance matrices. So I don't think it should be a feature in stringdist. however, here's an all base-R function that does exactly what you want (in less code than the tidy version):

```r
dmat_to_df <- function(x){
  d <- expand.grid(a=rownames(x), b=colnames(x))
  d$dist <- as.vector(u)
  d
}
```
To test, do:
```r
x <- c("apple", "banana", "peach")
y <- c("ape", "bandana", "pitch")
u <- stringdist::stringdistmatrix(a = x, b = y, useNames = "strings")
dmat_to_df(u)

```

**Comment by bschneidr** [comment]
Hi @markvanderloo,

Sorry for bothering you, then. Anyhow, thanks for the base-R function! It's a great solution to a common problem.

**Comment by markvanderloo** [comment]
Not a bother at all :-)

Cheers,
Mark
