### ISSUE TITLE
Double metaphone algorithm

### ISSUE THREAD

**Issue by nacnudus** [markvanderloo/stringdist#56]
This is a feature request for the double metaphone algorithm.  There is a [C++ implementation](https://github.com/slacy/double-metaphone).

**Comment by markvanderloo** [comment]
Thanks for the link! I definitely like to include it. It will take a bit of work to include since stringdist is C-based and works on int arrays (to handle encoding difference) and not on C++ strings. Also, it needs to be thread-safe since stringdist parallelizes everything with openMP.

**Comment by markvanderloo** [comment]
There is now a [phonics](https://cran.r-project.org/web/packages/phonics/index.html) package on CRAN where such a feature is more in its place.
