### ISSUE TITLE
Documentation Typo "Levensthein"

### ISSUE THREAD

**Issue by rexdouglass** [markvanderloo/stringdist#58]
stringdist version 0.9.4.6
stringdist-metrics {stringdist}	R Documentation
"Levenshtein distance"
"Damerau-Levensthein distance"

Both Levenshtein should be spelled identically, I believe.
https://en.wikipedia.org/wiki/Levenshtein_distance
https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance

**Comment by markvanderloo** [comment]
fixed
