### ISSUE TITLE
soundex distance

### ISSUE THREAD

**Issue by soodoku** [markvanderloo/stringdist#60]
dear mark,

soundex stringdist is a 1/0 based on whether codes match or not. I think that captures too little information. one way to preserve more information is to create a cosine distance or something similar between two soundex codes. there are smarter ways about thinking about 'distance' between sounds based on naive transcription errors etc. but I think a cosine distance at coded character level would be pretty useful. 

best,
gaurav

**Comment by markvanderloo** [comment]
Hi Gaurav,

You can easily do this with the package, although I'm not sure how to interpret a cosine distance between soundex codes of strings.
```r
> stringdist(phonetic("han solo"),phonetic("luke skywalker"),method="cosine")
[1] 0.3876276
```
For more sound-based distances, also see the [phonics package](https://cran.r-project.org/web/packages/phonics/index.html)
