### ISSUE TITLE
Word-level distance

### ISSUE THREAD

**Issue by leojoubert** [markvanderloo/stringdist#62]
Hi,

Many thanks for your wonderful package. Doing sequential analysis in social science, I would like to compute edit distance (`method = "lv"`) ideally with your package. However, my data are not character-level but -word level.

To give you an example, at word level edit sequence beetween `AW` and `DE` is 4 (2 deletions, 2 insertions). At word-level, it is 2 (deletions of `AW`, insertion of `DE`). My words are always 2 characters (in fact, they represent states in social sequences).

Is there a way to compute that with `stringdistmatrix` ?

**Comment by markvanderloo** [comment]
Sorry for the late reply.

Have you noticed the `seq_dist` function? If you tokenize a text and map each unique word to an integer, then you can use `seq_dist` to get distances between sequences of words.
