### ISSUE TITLE
compilation uses -fopenmp flag unavailable on macOS

### ISSUE THREAD

**Issue by schifferl** [markvanderloo/stringdist#63]
Without installing `clang4` `R` Binaries from https://github.com/coatless/r-macos-clang compilation on macOS will fail because `-fopenmp` flag is unavailable. This issue does not likely affect most users but is relevant to developers who must compile the package from source. It would be nice if the flag could be removed from `compile.sh` at line 5.

**Comment by markvanderloo** [comment]
It is not necessary to use `compile.sh` to build the package. I just use it to do quick checks when developing the `C` code, or to set some flags (e.g. for `valgrind`) when debugging. You can build the pkg from scratch with `R CMD build` as usual. On Mac w/o `clang4` you won't get multicore support but it will work.

**Comment by markvanderloo** [comment]
Or, if you do a pull, you can use `./build.sh`. This will generate docs, `R CMD build` and `R CMD check` with custom options you provide at the command line (e.g. `--as-cran`)
