### ISSUE TITLE
Exposing the pkg C API

### ISSUE THREAD

**Issue by ChrisMuir** [markvanderloo/stringdist#67]
Have you given any thought to exposing some of the internal functions that do the heavy lifting? I ask because I maintain a [package](https://github.com/ChrisMuir/refinr/blob/master/R/n_gram_merge.R#L128) that uses `stringdistmatrix()` like so:
```r
# Create a stringdistmatrix for every element of initial_clust.
distmatrices <- lapply(initial_clust, function(x) {
  as_matrix(stringdistmatrix(x, weight = weight, ...))
})
```
Obj `initial_clust` is a list of char vectors of various lengths, and when input is large this code chunk becomes a bottleneck. Just for testing purposes, I tried swapping in `stringdist:::lower_tri()` and saw a 23% speed boost, and I don't need to push all of the inputs through all of the validations at the top of `stringdistmatrix()` every time it's called.

I can't use `:::` to import `lower_tri()` because CRAN will complain. If it were just a single C function I could simply copy the function (with credit to the authors obv), but I'm currently giving users the option to choose any of the ten methods via ellipses.

I'd love to continue importing `stringdist` and be able to use `lower_tri()`.

**Comment by ChrisMuir** [comment]
An alternative (and maybe better solution) could be to create header files in `inst/include` that provide access to the `stringdist` C functions, and would allow for direct integration by another package using `LinkingTo` in the `DESCRIPTION` file of the other package. This would give package authors access to the `stringdist` C functions without exporting any additional R functions. Taking this approach, I could use the C function `R_lower_tri()` directly, and write my own wrapper for use in my pkg functions.

Check out [this](https://stackoverflow.com/questions/20474303/using-c-function-from-other-package-in-rcpp) SO post, and the answers by Romain and Dirk for more info.

And per Dirk's answer in that thread, here's an example in the wild, [rcppxts](https://github.com/eddelbuettel/rcppxts/blob/master/src/xtsMod.cpp) linking to and using C functions from the [xts](https://github.com/joshuaulrich/xts/blob/master/inst/include/xtsAPI.h) pkg.

If you're open to this idea, I'd be happy to work on implementation. Let me know if there's any interest. Thanks!

**Comment by markvanderloo** [comment]
Yeah exposing the C API is definitely on my list.

**Comment by ChrisMuir** [comment]
Cool! I can start working on implenenting changes next week, and can submit a PR. Let me know if you're okay with that, or if you have any thoughts/issues/concerns. Thanks Mark!

**Comment by ChrisMuir** [comment]
Hi Mark,

Thanks for the follow up and feedback. I actually worked on this some over the weekend, and last night pushed an initial first pass at making this work, check out the diffs [here](https://github.com/ChrisMuir/stringdist/commit/77dff6ce86886040d84682b232b17423c63ecfd8). I also created a new branch in my package [refinr](https://github.com/ChrisMuir/refinr/tree/c_api) that is LinkingTo `stringdist` and is using two of your C functions. Couple of things to mention (and keep in mind, this was just meant to be a rough proof concept to get the ball rolling):

- I modeled the edits to `stringdist` after package [xts](https://github.com/joshuaulrich/xts), so there's no C++ code involved, no dependency on `Rcpp`, and no new dependencies added.
- I went the route of exposing all of the `R_` C functions.
- In `refinr`, since I'm no longer directly calling any of the `stringdist` R functions, I was able to remove `stringdist` from `Imports` in my `DESCRIPTION` file (but added it to `LinkingTo`).
- With the way everything is currently set up, any pkg linking to `stringdist` can call `stringdist` C functions within its own C functions (see the `xts` [example package](https://github.com/joshuaulrich/xts/tree/master/inst/api_example)). In my package `refinr`, I'm able to do that, but I can also call `stringdist` C functions within R using `.Call()`. I think this is only because both of the `stringdist` functions I'm using are getting picked up by `RcppExports.cpp`, but I'm not sure about that.

To briefly map out how `refinr` is using the `stringdist` C API, see the last two functions in my [utils.R](https://github.com/ChrisMuir/refinr/blob/c_api/R/utils.R) file. Func `lower_tri()` is calling `sd_lower_tri()`. Func `get_list_lengths()` is calling a C function I added to `refinr` in file `refinr/src/stringdist.c`, which is calling `sd_lengths()`. Both of the `sd_` functions are pointing back to your C functions (the `R_` versions) via file `stringdist/pkg/inst/include/stringdist_api.h`. I'm not using `get_list_lengths()` in my pkg, but added the function just to test, and it's working:
```r
refinr:::get_list_lengths(list(c(1, 2, 3), c("cats", "dogs")))
#> [1] 3 2
```

I worked on these edits on a PC, and everything works so far. I plan to test it all on a Mac today. I also set up my forked `stringdist` repo on Travis, and the `c_api` branch [passed](https://travis-ci.org/ChrisMuir/stringdist), so that's a good sign.

**Comment by ChrisMuir** [comment]
I think we can close this issue now.....C API has been built out and is exposed as of version 0.9.5.1.
