### ISSUE TITLE
soundex empty issue

### ISSUE THREAD

**Issue by KyleHaynes** [markvanderloo/stringdist#71]
Hi Mark,
Do you consider it correct to return an empty string as "0000" with the phonetic (soundex) function?
```R
stringdist::phonetic("")
[1] "0000"
```

From https://en.wikipedia.org/wiki/Soundex
> The Soundex code for a name consists of a letter followed by three numerical digits

Nothing is not 0?

I'm interested in your thoughts or if you would consider this a bug.

Cheers
Kyle

**Comment by markvanderloo** [comment]
Nice edge case :-).

I'm currently on vacation with my family but I'll give it some thought after i'm back.

My first guess is that soundex is not even defined for the empty string, given its origin.

Cheers,
M

**Comment by markvanderloo** [comment]
In cases like this I go to my bookcase and open [TACP](https://en.wikipedia.org/wiki/The_Art_of_Computer_Programming), part 3, page 394. There is no definition of the algorithm when there is no first letter.

But actually, the answer is already in the wikipedia definition you cite:

> The Soundex code for a **name** consists of a letter followed by three numerical digits

An empty string is not a name :-).

So, I think we can leave it safely at `0000` and no-one will get hurt.
