### ISSUE TITLE
Issue with LCS method - Incorrect distance

### ISSUE THREAD

**Issue by harikumarm01** [markvanderloo/stringdist#77]
I was checking the accuracy of various pattern matching methods available in the strinddist package of R. 

For the below input, lcs method gave output as 8 while other methods gave output as 5

> stringdist("101247591 secondpart third","101301261 secondpart third",method="lcs")
[1] 8 - **incorrect**
> stringdist("101247591 secondpart third","101301261 secondpart third",method="dl")
[1] 5
> stringdist("101247591 secondpart third","101301261 secondpart third",method="lv")
[1] 5
> stringdist("101247591 secondpart third","101301261 secondpart third",method="osa")
[1] 5

**Comment by markvanderloo** [comment]
Why would you expect different methods to give the same result? Each method represents a different way to measure how different two strings are. See 
````
?`stringdist-metrics`
````
or the [r-journal paper](https://journal.r-project.org/archive/2014-1/loo.pdf) for a brief overview of the differences.

**Comment by harikumarm01** [comment]
@markvanderloo ,

Thanks for your time and the clarification. I overlooked Longest Common Substring to Levenshtein distance. my bad
