### ISSUE TITLE
Cannot install from CRAN

### ISSUE THREAD

**Issue by lajoimat** [markvanderloo/stringdist#80]
Hello,

I'm getting that error when I try to install.

Thanks

>  install.packages("stringdist")
> 
>   There is a binary version available but the source version is later:
>             binary  source needs_compilation
> stringdist 0.9.5.1 0.9.5.5              TRUE
> 
> Do you want to install from sources the package which needs compilation? (Yes/no/cancel) no
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/stringdist_0.9.5.1.tgz'
> Warning in install.packages :
>   cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/stringdist_0.9.5.1.tgz': HTTP status was '404 Not Found'
> Error in download.file(url, destfile, method, mode = "wb", ...) : 
>   cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/stringdist_0.9.5.1.tgz'

**Comment by markvanderloo** [comment]
Hi there,

It is not a `stringdist` issue. I don't understand why it is trying to download version 0.9.5.1 because version 0.9.5.5 [has been available](https://CRAN.r-project.org/package=stringdist) since 21 Oktober 2019.
