### ISSUE TITLE
I can't seem to compile this package on Windows 10?

### ISSUE THREAD

**Issue by xiaodaigh** [markvanderloo/stringdist#82]
See [SO issue](https://stackoverflow.com/questions/60362938/r-unable-to-run-pdflatex-on-xxxx-text)

I tried to compile this package on Windows 10 and I just get the error

```
E  creating vignettes (3.7s)
   --- re-building 'RJournal_6_111-122-2014.Rnw' using Sweave
   Error: processing vignette 'RJournal_6_111-122-2014.Rnw' failed with diagnostics:
   unable to run 'pdflatex' on 'RJournal_6_111-122-2014.tex'
   --- failed re-building 'RJournal_6_111-122-2014.Rnw'  
```

Was this tested on Windows 10 or Just Linxu and Mac?

**Comment by markvanderloo** [comment]
Hi there

The [CRAN test results](https://cran.r-project.org/web/checks/check_results_stringdist.html) show that it builds fine on 3 different flavours of Windows and R. 

I see that the vignette is not building. Perhaps your latex installation is not working correctly?

**Comment by xiaodaigh** [comment]
Thanks for the reply I will try it on Ubuntu and on Windows I will reinstall MikTex and see if that helps. Currently I use the TinyTex that was installed by the R package tinytex, but maybe that's the cause. Thanks for pointing out the info.
