### ISSUE TITLE
Source code stringdist methods

### ISSUE THREAD

**Issue by PythonMonkey89** [markvanderloo/stringdist#83]
Hi,

I am currently trying to implement a word-level Damerau-Levenshtein distance to use on a few texts. The stringdist function returns the distance between individual characters, so I was thinking that I could “change” this function to work on word-level distance. I had a look at the stringdist source code, but it does not include the source code for the various methods specifically. What are these methods based on - or would it be possible to get access to this specific source code?

Thank you

**Comment by markvanderloo** [comment]
Hi,

if you create a charcter vector where each element contains one word (`e.g.` using `strsplit`), and then convert each word to a unique integer (e.g. using `hashr::hash`) then you can get the distance you want with `stringdist::seq_dist`. Here's an example.

```r
x <- c("aap", "noot", "mies")
y <- c("noot", "aap", "mies")
seq_dist(hash(x),hash(y))
[1] 1
seq_dist(has(x), has(y), method="lv")
[1] 2
```
