### ISSUE TITLE
BiocCheck requires stringdist but cannot install it

### ISSUE THREAD

**Issue by shokoohi** [markvanderloo/stringdist#84]
I get the following error while trying to install your software. I tried every possible solution I could find but it did not work. 
I am using R 4 dev version. 

> BiocManager::install("stringdist")
Bioconductor version 3.11 (BiocManager 1.30.10), R Under development (unstable) (2020-03-15 r77975)
Installing package(s) 'stringdist'
Warning: unable to access index for repository https://cran.rstudio.com/bin/macosx/el-capitan/contrib/4.0:
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/4.0/PACKAGES'
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘stringdist’
Do you want to attempt to install these from sources? (Yes/no/cancel) Yes
installing the source package stringdist
trying URL https://cran.rstudio.com/src/contrib/stringdist_0.9.5.5.tar.gz
Content type 'application/x-gzip' length 831912 bytes (812 KB)
==================================================
downloaded 812 KB
 installing *source* package ‘stringdist’ ...
** package ‘stringdist’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fopenmp -fPIC  -Wall -g -O2  -c R_register_native.c -o R_register_native.o
clang: error: unsupported option '-fopenmp'
make: *** [R_register_native.o] Error 1
ERROR: compilation failed for package ‘stringdist’
 removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/stringdist’
The downloaded source packages are in
	‘/private/var/folders/9q/88hxnskx4kg30vgg73y4nzl40000gn/T/Rtmp3wVdL1/downloaded_packages’
Warning message:
In install.packages(...) :
  installation of package ‘stringdist’ had non-zero exit status

**Comment by markvanderloo** [comment]
CLANG does not support openmp parallelization. Normally you don't notice this because CRAN builds Mac binaries for you.

Since I don't own a Mac I'm not sure how to solve it. Perhaps if you download from gh and build the pkg yourself?

**Comment by shokoohi** [comment]
It does not work. Hopefully bioconductor will fix this problem soon in case you are not willing to make it compatible with Mac.

**Comment by idno0001** [comment]
@shokoohi I was having the same issue. The steps in the following comment fixed it for me:
https://github.com/velocyto-team/velocyto.R/issues/57#issuecomment-506671728

**Comment by shokoohi** [comment]
Perfect. It works now. Thank you.

**Comment by markvanderloo** [comment]
@shokoohi just be clear: it is not about me making stringdist compatible with Mac. Since CRAN delivers Mac binaries, it clearly is compatible.

**Comment by brooksambrose** [comment]
fwiw I have stringdist working with openmp on an M1 mac using the generic instructions here: https://mac.r-project.org/openmp/ and building stringdist from source

```zsh
curl -O https://mac.r-project.org/openmp/openmp-14.0.6-darwin20-Release.tar.gz
sudo tar fvxz openmp-14.0.6-darwin20-Release.tar.gz -C /
```

```r
remove.packages("stringdist")
install.packages("stringdist", type = "source")
```

I believe I already had gfortran installed when I did the same for the data.table package, so not sure if that will be necessary but hope this helps anyone else looking for a solution.
