### ISSUE TITLE
stringsimmatrix not containing the same values as stringsim

### ISSUE THREAD

**Issue by tamas-ferenci** [markvanderloo/stringdist#88]
I might overlook something, but I don't understand how this is possible:

```
temp<-c("ca", "abc", "cba")
stringdist::stringsimmatrix(temp)
```

I.e., that the (1,3) element is not the same as (3,1). The latter seems to be correct as `stringdist::stringsim(temp[1], temp[3])==stringdist::stringsim(temp[3], temp[1])==0.6666667`.

**Comment by markvanderloo** [comment]
confirmed: its a bug. Thanks for reporting

**Comment by tamas-ferenci** [comment]
You're welcome, thanks for confirming it!
