### ISSUE TITLE
stringdist/stringsim result when q > x & y

### ISSUE THREAD

**Issue by arthurgailes** [markvanderloo/stringdist#92]
Hello,

I'm encountering a strange result from the following function:  `stringsim("D", "R", method = 'cosine', q=2)`, which returns 0 (or 1 for stringdist)

The docs state: "The computation is aborted when q is is larger than the length of any of the strings. In that case Inf is returned."

This is understandable, but the qgram method seems to return NaN/0, rather than infinity, and furthermore, this seems to be the opposite of anybody's intended result. Would it be possible to return the opposite answer to this question? If `stringsim` is fed two characters less than q, those two strings are by definition completely dissimilar (either 0 or NA for `stringsim`, and either 1 or NA for `stringdist`)

Thank you for your time and hard work.

**Comment by fabiocs8** [comment]
Same issue here. Regarding the output value, I believe that an NA would be more consistent. Because x and y < q, then the result is meaningless, rather than dissimilar = 1.

**Comment by markvanderloo** [comment]
Please see the discussion in #96
