### ISSUE TITLE
feature request: supply pre-encoded strings to stringdist

### ISSUE THREAD

**Issue by rubenalv** [markvanderloo/stringdist#94]
Hello,
For very long vectors (eg I have a vector of length 1e5) a distance matrix is generally not a viable option due to insufficient RAM.
In my vector I want to discard strings that pass a threshold of similarity, so my approach involves looping (at the R level) for each element of the vector over the remaining elements after it. I store the positions that pass the threshold, and remove them at the end. Since I am reusing the same long vector, and stringdist automatically re-encodes it, if the vector was supplied already encoded to stringdist that would avoid the overhead in each loop. I am assuming the overhead is significant enough to make a difference.
Great package.

**Comment by djvanderlaan** [comment]
With `seqdist` you are able to calculate distances between sequences of integers. So you could convert your strings to (utf8 and then to) integer (which is also what `stringdist` does)  and then call `seqdist`. Or if your strings can be encoded in less than 256 characters (perhaps some local encoding such as latin1), then you can use the `useBytes` option of `stringdist`.

**Comment by markvanderloo** [comment]
I think that the [refinr](https://cran.r-project.org/package=refinr) package does what you want. It uses the stringdist C api, so no R-level loops.

**Comment by rubenalv** [comment]
appreciated, thanks!
