### ISSUE TITLE
Value of Jaro-Winkler distance different from the ones calculated in Python

### ISSUE THREAD

**Issue by lucazav** [markvanderloo/stringdist#99]
I'm testing the Jaro-Winkler similarity provided by `stringdist` and I'm comparing its result with the output of two Python libraries: TextDistance and RapidFuzz.

Using TextDistance, I get this result:

```
import textdistance
email1 = 'bmartinez@example.com'
email2 = 'landerson@example.com'
textdistance.jaro_winkler(s1=email1, s2=email2, prefix_weight=0.1)
```
> 0.8204365079365079

Using RapidFuzz, I get the same result:

```
from rapidfuzz.distance import JaroWinkler
email1 = 'bmartinez@example.com'
email2 = 'landerson@example.com'
JaroWinkler.similarity(s1=email1, s2=email2, prefix_weight=0.1)
```
> 0.8204365079365079

Running the equivalent code in R using stringdist, I get a different result:

```
library(stringdist)
email1 = 'bmartinez@example.com'
email2 = 'landerson@example.com'
stringsim(email1, email2, method = 'jw', p = 0.1)
```
> 0.8100198

Is there some parameter I'm missing in `stringdist` that causes this different output?

**Comment by markvanderloo** [comment]
Hi there. This may be because of the fact that the Jaro distance is poorly documented. The implementation in `stringdist` is based on the original 1960s manual that describes step-by-step how it is computed.
